#version: "3.3"
#
#services:
#  mongo:
#    image: mongo:4.2
#    restart: always
#    ports:
#      - 27017:27017
#
#  mongo-express:
#    image: mongo-express
#    hostname: mongo-express
#    container_name: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#
##mongo-client:
#        ##    image: mongoclient/mongoclient
#        ##    ports:
#        ##      - 3030:3000
#        ##    environment:
#        ##      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017
#      ##    links:
#      ##      - mongo
#
#  app:
#    image: frankluxiao/gradle-spring-boot-mongodb
#    ports:
#      - 8080:8080
#    links:
#      - mongo
#    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar app.jar"
#    depends_on:
#      - mongo
